#00.pytorch fundamentals:


In [3]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [4]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


#Introduction to Tensors:


creating tensors


In [5]:
#scaler
#pytorch tensors are created using to torch.tensor()
scaler=torch.tensor(7)
scaler

tensor(7)

In [6]:
scaler.ndim

0

In [7]:
#get the integer back from tensor:
scaler.item()

7

In [8]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [13]:
vector.tolist()

[7, 7]

In [15]:
#matrix
metrix=torch.tensor([[7,8],
                     [9,10]])
metrix

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
metrix.ndim

2

In [18]:
metrix[1]

tensor([ 9, 10])

In [20]:
metrix.shape

torch.Size([2, 2])

In [31]:
#tensor
ten=torch.tensor([
    [[1,2,3],
    [12,3,4],
    [1,4,5]],
    [[2,3,4],
     [3,4,5],
     [23,3,4]],
    [[1,2,3],
     [2,3,4],
     [3,4,5]]
    ])
ten

tensor([[[ 1,  2,  3],
         [12,  3,  4],
         [ 1,  4,  5]],

        [[ 2,  3,  4],
         [ 3,  4,  5],
         [23,  3,  4]],

        [[ 1,  2,  3],
         [ 2,  3,  4],
         [ 3,  4,  5]]])

In [32]:
ten.ndim

3

In [33]:
ten.shape
#([1,3,3]) means we have one 3x3 tensor

torch.Size([3, 3, 3])

In [38]:
ten[2][0]

tensor([1, 2, 3])

###random tensor

#why random tensors??
#random tensors are important beacuse the way many neural network learn is that
#they start with tensors full of random numbers and then adjust those random numbers to better represent
#the data....
#start with random number->look the data->update random numbers->look the data->
#update random numbers..and so on

In [39]:
#create random number...
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.6491, 0.8528, 0.4445, 0.8182],
        [0.5701, 0.3743, 0.5696, 0.7117],
        [0.7048, 0.0755, 0.8433, 0.4500]])

In [43]:
random_tensor[1][0]

tensor(0.5701)

In [44]:
random_tensor.ndim

2

In [45]:
random_tensor.shape

torch.Size([3, 4])

In [47]:
#create a random tensor with similar shape to image tensor
random_image_size_tensor=torch.rand(size=(3,224,224))#height,width,color channel (R,G,B)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

###zeroes and ones

In [48]:
#create a tensor full of zeroes and ones
zero_tensor=torch.zeros(3,4)
zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [53]:
#multiplying to tensors:
zero_tensor[0][1]*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [54]:
#create tensor of all ones:
ones_tensor=torch.ones(3,4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [56]:
ones_tensor.dtype

torch.float32

###create a range of tensor and tensor-like---


In [65]:
#use torch.range()
zero_ninty=torch.arange(0,100,10) # start,end,step

In [68]:
#creating tensor-like
tensor_zero=torch.zeros_like(zero_ninty)
tensor_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [71]:
#practice of lookalike:
TENSOR=torch.rand(3,4)
TENSOR_LOOKALIKE_ZERO=torch.ones_like(TENSOR)
TENSOR_LOOKALIKE_ZERO

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

###tensors Datatype:


**Note** Tensor datatypes is one of the 3 big errors you'll run into with PYtorch & deeplearning:
1.Tensors not right datatype.
2.Tensors not right shape.
3.Tensors not on the right device.

In [75]:
#float 32 Dtype:
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None)
float_16_tensor=torch.tensor([3.0,9.0,6.0],
                             dtype=torch.float16,#what datatype is the tensor..
                             device=None,#None is "CPU" by default #what device your tensor is on...
                             requires_grad=False #if we want to track gradients of this tensor...
                             )
float_32_tensor
float_32_tensor.dtype ##default datatype for tensors in pytorch is float32
float_16_tensor.dtype

torch.float16

In [76]:
#converting float32 tensor to float16 tensor:
float_16_tensor_con=float_32_tensor.type(torch.float16)
float_16_tensor_con
#this help us to tackle the first error that we encounter while using datatpe:
#tensor of not same datatype....

tensor([3., 6., 9.], dtype=torch.float16)

In [81]:
mul=float_16_tensor*float_32_tensor
mul.dtype
# In PyTorch, when you perform operations on tensors with different data types,
#it automatically promotes them to a common compatible dtype before performing the operation — this is called type promotion or type inference.

torch.float32