<a href="https://colab.research.google.com/github/yashraj01-se/Pytorchrepo/blob/main/Pytorch_fundamentals_tensors_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensor Manipulation:

In [ ]:
#reshaping,stacking,squeezing and unsquezzind tensors:
#reshaping-reshape the input tensor to a defined shape...
#view-return a view of a input tensor of certain shape but keep the same
#memory as the original tensor.
#stackig-combining multiple tensors on the top of each other(vstack) and side by side (hstack)
#squeeze-remove all 1 dimension from a tensor.
#unsqueeze-add a 1 dimension to the taget tensor.
#permute-return a view of the input with differnt dimension permuted (swapped) in a certain way...


In [33]:
import torch
x=torch.arange(1,10)
x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [34]:
#reshape: Add an extra dimension:
x_re=x.reshape(1,9)#ek dimension 9 ke size of tensor me....(dimension,size) // by -1 the pytorch will auto matically understand the reshaping...
x_re,x_re.shape



(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [21]:
#change the view:
z=x.view(4,3) #z is just a different view of x
z,z.shape

(tensor([[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([4, 3]))

In [ ]:
#changing z will change the x because they share same memory location

In [22]:
z[:0]=5
z,x


(tensor([[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]),
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]))

In [28]:
#stack tensor on top:
x_stack=torch.stack([x,x,x,x],dim=0)# dim=0(vertical stack), dim=1(horizontal stack)
x_stack

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [24]:
#squeeze:
x_sq=torch.squeeze(x_stack)
x_sq   # because no one dimension....

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [43]:
print("previous:",x_re)
print("previous shape:",x_re.shape)

previous: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
previous shape: torch.Size([1, 9])


In [53]:
x_squeezed=x_re.squeeze()
print("now after squeeze:",x_re.squeeze())
print("shape after:",x_re.squeeze().shape)

now after squeeze: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
shape after: torch.Size([9])


In [54]:
#add another dimension at specific dim....
print("now after unsqueeze:",x_squeezed.unsqueeze(dim=0))
print("shape after unsqueeze:",x_re.squeeze().shape)

now after unsqueeze: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
shape after unsqueeze: torch.Size([9])


In [58]:
x_re

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [71]:
#torch.permute -rearranges the dimensions of target tensor in a specified order...
#mainly used with image data...
x_pert=torch.rand(224,224,3) #[height,width,colour channel]
x_p=torch.permute(x_pert,(2,0,1))
print("prev shape: ",x_pert.shape)
print("after permutation: ",x_p.shape) #[colour_channel,height,width] #basically a  differnt a view

prev shape:  torch.Size([224, 224, 3])
after permutation:  torch.Size([3, 224, 224])


In [77]:
x_pert[0,0,0]=7232
x_p#this shows that value remain same just view changes...because of same memory shared...

tensor([[[7.2320e+03, 4.6204e-01, 3.4591e-01,  ..., 7.5934e-02,
          8.4687e-01, 9.4467e-01],
         [3.3977e-01, 1.7016e-01, 3.2916e-01,  ..., 8.5748e-01,
          2.5636e-01, 3.6475e-01],
         [3.9450e-01, 4.9686e-01, 7.4590e-01,  ..., 5.3999e-01,
          3.7921e-02, 8.7819e-01],
         ...,
         [2.3075e-01, 9.9127e-01, 2.8417e-02,  ..., 7.5877e-01,
          2.6656e-01, 8.0532e-01],
         [6.9465e-01, 5.7022e-01, 3.9514e-01,  ..., 9.8191e-02,
          4.7284e-01, 3.1127e-01],
         [8.5638e-01, 6.8553e-01, 8.3080e-02,  ..., 8.6831e-01,
          2.6449e-01, 2.0815e-01]],

        [[1.3835e-01, 2.3525e-01, 4.3798e-01,  ..., 2.7950e-01,
          2.1861e-01, 2.7182e-01],
         [6.4712e-01, 3.6155e-01, 1.3387e-01,  ..., 7.8666e-01,
          9.1759e-01, 3.1640e-02],
         [9.7822e-01, 7.6138e-01, 7.5369e-01,  ..., 4.6394e-01,
          9.4780e-01, 8.0648e-01],
         ...,
         [3.1378e-01, 7.9865e-01, 2.9515e-01,  ..., 2.2915e-01,
          9.011

#selecting data from tensors (indexing)


In [80]:
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [85]:
#indexing--
x[0]

tensor(8)

In [86]:
#middle bracket--
x[0,1]

tensor([4, 5, 6])

In [90]:
#specific inner braceket--
x[0,2,2]

tensor(9)

In [97]:
#you can also use ":" to select "all" of a target dimension:
x[:,0]
x[:,0,1]
x[0,1,:]

tensor([4, 5, 6])

In [98]:
#get all the values of 0th and 1st dim but only index 1 of 2nd diomension:
x[:,:,1]

tensor([[2, 5, 8]])

In [99]:
#get all values of the 0 dimension but only the 1 index of 1st and 2nd dim..
x[:,1,1]

tensor([5])

In [100]:
#get index 0 of 0th and 1st dimension and all values of 2nd dim..
x[0,0,:]

tensor([1, 2, 3])

In [101]:
#retrun 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

Pytorch tensors & numpy

In [ ]:
#most of the time we start with numpy array that is needed to be converted into tensor using ->torch.from_numpy(name_numpy_array
#and tensor to numpy:->torch.Tensor.numpy()

In [124]:
#numpy to tensor:
import torch
import numpy as np
df=np.arange(1.0,4.0)
df_t=torch.from_numpy(df).type(torch.float32)
df.dtype,df_t.dtype


(dtype('float64'), torch.float32)

In [125]:
#if we try to cahnge the value of array will it affect the value of tensor??
df=df+1;
df,df_t  #hence proves that array and tensor remains differnt and changing the value of array will not affect the value of tensor....

(array([2., 3., 4.]), tensor([1., 2., 3.]))

In [126]:
#tensor to numpy:
ten_to_num=df_t.numpy()
ten_to_num,df_t

(array([1., 2., 3.], dtype=float32), tensor([1., 2., 3.]))

In [127]:
#if we try to change the value of tensor will it affect the value of array??
df_t=df+1
ten_to_num,df_t #proves value do not changes...

(array([1., 2., 3.], dtype=float32), array([3., 4., 5.]))

Pytorch reproducebility-(taking random out of random)

In [ ]:
#to reduce the randomness in neural network and pytorch comes the concept of **RANDOM SEED**

In [ ]:
#basically the random seed "Flavours" the randomness ...#It helps in reproducibility (getting the same result every time for testing or debugging).

In [128]:
import torch
ran_A=torch.rand(3,4)
ran_B=torch.rand(3,4)
print(ran_A)
print(ran_B)
print(ran_A==ran_B)

tensor([[0.2335, 0.9430, 0.5573, 0.3630],
        [0.0570, 0.3983, 0.8556, 0.5567],
        [0.4918, 0.7970, 0.7846, 0.2642]])
tensor([[0.6982, 0.7886, 0.5917, 0.1074],
        [0.5639, 0.5175, 0.4799, 0.7235],
        [0.5053, 0.4453, 0.2152, 0.2303]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [131]:
#make it reproducable...
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
ran_c=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED) #remember each time we have to call torch_manual
ran_d=torch.rand(3,4)
print(ran_c)
print(ran_d)
print(ran_c==ran_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
