<a href="https://colab.research.google.com/github/yashraj01-se/Pytorchrepo/blob/main/pytorch_fundamentals_tensors_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
int_32_tensor=torch.tensor([1,2,3],dtype=torch.int32,device="cpu",requires_grad=False)
float_32_tensor=torch.tensor([1.0,2.0,3.0],dtype=torch.float32,device="cpu",requires_grad=False)
int_32_tensor*float_32_tensor

tensor([1., 4., 9.])

###Getting information from tensors:
1.tensor not right datatype:to do get datatype from a tensor,can use "tensor.dtype"
2.tensor to get right shape:use "tensor.shape"
3.tensor on right device:use "tensor.device"

In [4]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.5100, 0.2987, 0.1020, 0.1837],
        [0.6343, 0.7560, 0.4420, 0.5419],
        [0.7630, 0.5910, 0.3457, 0.1962]])

In [5]:
#details about above tensor:
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

torch.float32
torch.Size([3, 4])
cpu


In [7]:
#if we want to change the details:
changed_tensor=torch.rand(dtype=torch.float16,device="cuda",size=(4,4))
print(changed_tensor.dtype)
print(changed_tensor.shape)
print(changed_tensor.device)

torch.float16
torch.Size([4, 4])
cuda:0


###Manipulating tensors

#tensor operations:
#1.ADD 2.Sub 3.Mul 4.Division 5.Matrix mul


In [13]:
tensor=torch.tensor([1,2,3])
tensor+10
tensor*10
tensor-10
#inbult function of pytorch:
torch.mul(tensor,10)
torch.add(tensor,10)

tensor([11, 12, 13])

In [24]:
#matrix mul:(dot product)
#two main rule of Matrix multiplication:
#1.inner dimension must match
#(2,3)@(2,3) will wont work but (2,3)@(3,2) will work...
#2.the result will be the shape of outter dimensions....
first_tensor=torch.tensor([[1,2,3],
                           [1,2,3],
                           ])
print(first_tensor.shape)
second_tensor=torch.tensor([[1,2,3],
                            [1,2,3],
                            [1,2,3]])
print(second_tensor.shape)
answer=torch.matmul(first_tensor,second_tensor)
print(answer)
print(answer.shape)#outter dimension shape...

torch.Size([2, 3])
torch.Size([3, 3])
tensor([[ 6, 12, 18],
        [ 6, 12, 18]])
torch.Size([2, 3])


###one of the most common errors in deep learning :shape error

In [37]:
first_tensor=torch.tensor([[1,2],
                           [1,2],
                           [1,2]])

second_tensor=torch.tensor([[1,2],
                            [1,2],
                            [1,2]])
print("shapes before transpose: ",first_tensor.shape,second_tensor.shape)
#how to adjust to matix whose shpe does not matches with the first fule of matrix multipliaction....
#using transpose
second_tensor=second_tensor.T
print("shape after transpose: ",first_tensor.shape,second_tensor.shape)
answer=torch.matmul(first_tensor,second_tensor)
print(answer)
print(answer.shape)

shapes before transpose:  torch.Size([3, 2]) torch.Size([3, 2])
shape after transpose:  torch.Size([3, 2]) torch.Size([2, 3])
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])
torch.Size([3, 3])


###finding the min, max ,sum etc(tensor aggregation)

In [50]:
x=torch.arange(0,100,10)
print(x)
x_min=torch.min(x)
print("min: ",x_min)
x_max=torch.max(x)
print("max: ",x_max)
#mean requires float32 but default is int64 so change:
x_mean=torch.mean(x.type(torch.float32))
print(x_mean)
x_sum=torch.sum(x)
print(x_sum)



tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
min:  tensor(0)
max:  tensor(90)
tensor(45.)
tensor(450)


#Finding the positional min and max:


In [53]:
ten=torch.tensor([2,3,1,5])
#return index position of min and max:
print(torch.argmin(ten))
print(torch.argmax(ten))


tensor(2)
tensor(3)
